# Generated by Django 5.1.7 on 2025-03-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0003_cook_is_chef_alter_cook_years_of_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="position",
            field=models.CharField(max_length=65, null=True),
        ),
    ]
