# Generated by Django 5.1.7 on 2025-03-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0004_cook_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cook",
            name="position",
        ),
    ]
