# Generated by Django 5.1.7 on 2025-05-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0005_remove_cook_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishtype",
            name="child_types",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtypes",
                to="kitchenflow.dishtype",
            ),
        ),
    ]
