# Generated by Django 5.1.7 on 2025-05-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0006_dishtype_child_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dishtype",
            old_name="child_types",
            new_name="parent",
        ),
    ]
