# Generated by Django 5.1.7 on 2025-05-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0007_rename_child_types_dishtype_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishtype",
            name="parent",
        ),
        migrations.AddField(
            model_name="dishtype",
            name="child_types",
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dishtype",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtypes",
                to="kitchenflow.dishtype",
            ),
        ),
    ]
