# Generated by Django 5.1.7 on 2025-05-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0008_remove_dishtype_parent_dishtype_child_types_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishtype",
            name="child_types",
        ),
        migrations.AlterField(
            model_name="dishtype",
            name="name",
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
