# Generated by Django 5.1.7 on 2025-06-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0010_ingredient_dishingredient_dish_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishingredient",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="kitchenflow.dish",
            ),
        ),
    ]
