# Generated by Django 5.1.7 on 2025-06-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0012_ingredienttype_ingredient_ingredient_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="ingredient_type",
            new_name="type",
        ),
    ]
