# Generated by Django 5.1.7 on 2025-06-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0013_rename_ingredient_type_ingredient_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="type",
            new_name="ingredient_type",
        ),
    ]
