# Generated by Django 5.1.7 on 2025-06-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0014_rename_type_ingredient_ingredient_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["ingredient_type", "name"]},
        ),
    ]
