# Generated by Django 5.1.7 on 2025-07-01 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0015_alter_ingredient_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="kitchenflow.ingredienttype",
            ),
        ),
    ]
