# Generated by Django 5.1.7 on 2025-07-06 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0016_alter_ingredient_ingredient_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishingredient",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_ingredients",
                to="kitchenflow.dish",
            ),
        ),
    ]
