# Generated by Django 5.1.7 on 2025-07-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0018_alter_dishingredient_dish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishingredient",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes_ingredients",
                to="kitchenflow.dish",
            ),
        ),
    ]
