# Generated by Django 5.1.7 on 2025-07-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0020_alter_dishingredient_dish"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name", "ingredient_type"]},
        ),
    ]
