# Generated by Django 5.1.7 on 2025-07-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenflow", "0021_alter_ingredient_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="recipe",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="dishingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "gram"),
                    ("kg", "kilogram"),
                    ("ml", "milliliter"),
                    ("l", "liter"),
                    ("pcs", "piece"),
                    ("tbsp", "tablespoon"),
                    ("tsp", "teaspoon"),
                    ("sl", "slice"),
                ],
                max_length=10,
            ),
        ),
    ]
